learning_rate: 1e-1
weight_decay: 5e-4
momentum: 0

gradient_clip:
    rate: 


lr_schedule:
    warmup:
        epochs: 5
        start_lr: 1e-2

    decay_milestones: [100, 250, 400, 550, 700]
    factor: 0.1