learning_rate: 5e-2
weight_decay: 5e-4
momentum: 0

gradient_clip:
    rate: 


lr_schedule:
    warmup:
      epochs: 5
      start_lr: 0.01
      
    decay_milestones: [150, 300, 450]

    factor: 0.1