hydra:
  run:
    dir: ./${run_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: ./${run_name}/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${mixing_matrix}-gradient:${old_gradients}-equal_test_set:${same_distrib_test_set}
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.joblib_launcher.JoblibLauncher
    n_jobs: -1
    backend: null
    prefer: processes
    require: null
    verbose: 0
    timeout: null
    pre_dispatch: 2*n_jobs
    batch_size: auto
    temp_folder: null
    max_nbytes: null
    mmap_mode: r
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - same_distrib_set=true,false
    - mixing_matrix=metropolis_hasting,maximum_degree,jaccard
  job:
    name: main
    chdir: null
    override_dirname: mixing_matrix=metropolis_hasting,maximum_degree,jaccard,same_distrib_set=true,false
    id: ???
    num: ???
    config_name: config
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /home/tanguy/FLP2P
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/tanguy/FLP2P/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      graph: two_clusters
      train: default
      client: default
      partition: dirichlet
      model: lenet5
      data: cifar10
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: joblib
      hydra/output: default
  verbose: false
data:
  name: cifar10
  root: ./data
  batch_size: 10
  num_workers: 0
model:
  name: lenet5
  latent_dimension: 1600
  num_classes: 10
  in_channels: 3
  batch_norm: false
partition:
  name: dirichlet
  num_clients: 80
  strategy: dirichlet
  dirichlet_alpha: 0.1
  min_partition_size: 1
client:
  learning_rate: 0.01
  weight_decay: 0.0005
  momentum: 0
train:
  rounds: 1000
  local_epochs: 1
  progress: true
  lr_decay: 0.99
graph:
  name: two_clusters
  topology: two_clusters
  main_link_activation: 1
  border_link_activation: 1
seed: 42
use_cuda: true
mixing_matrix: metropolis_hasting
run_name: DSGD_full_activation
old_gradients: false
same_distrib_test_set: false
